---
driver:
  name: docker
platforms:
  - name: ${MOLECULE_NAME}
    image: ${MOLECULE_DISTRO}
    pre_build_image: false
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
