---
- name: Verify
  hosts: all
  gather_facts: true
  tasks:
    - name: Lowercase OS Family
      ansible.builtin.set_fact:
        __os_family: "{{ ansible_facts['os_family'] | lower }}"

    - name: Include OS variables
      ansible.builtin.include_vars: "{{ item }}"
      with_first_found:
        - "{{ __os_family }}-{{ '12+' if ((ansible_facts['distribution_major_version'] | int ) >= 12 ) }}.yml"
        - "{{ __os_family }}.yml"

    - name: Validate restrict config
      ansible.builtin.lineinfile:
        path: "{{ __ntp_config_file }}"
        line: "restrict 10.10.10.10 nomodify nopeer limited"
      check_mode: true
      register: restrict_line

    - name: Restrict config is correct
      ansible.builtin.assert:
        that:
          - not restrict_line.changed
