---
- name: Restart NTP
  ansible.builtin.service:
    name: "{{ ntp_daemon | default(__ntp_daemon) }}"
    state: restarted

- name: Restart cron
  ansible.builtin.service:
    name: cron
    state: restarted

- name: Restart rsyslog
  ansible.builtin.service:
    name: rsyslog
    state: restarted
