---
name: Validate Collection
"on":
  pull_request:
  push:
    paths-ignore:
      - "docs/**"

defaults:
  run:
    working-directory: ".ansible/collections/ansible_collections/rgon10/general"

jobs:
  lint:
    name: Ansible Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
      - name: Run Ansible-Lint
        uses: ansible/ansible-lint@main

  molecule:
    name: Molecule
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro:
          - name: debian12
            image: debian:bookworm
          - name: debian11
            image: debian:bullseye

    steps:
      - name: Check out the codebase
        uses: actions/checkout@v4
        with:
          path: ".ansible/collections/ansible_collections/rgon10/general"

      - name: Set up Python 3.
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install test dependencies.
        run: pip3 install ansible molecule molecule-plugins[docker] docker

      - name: Run Molecule tests
        run: molecule test --all
        env:
          PY_COLORS: "1"
          ANSIBLE_FORCE_COLOR: "1"
          MOLECULE_DISTRO: ${{ matrix.distro.image }}
          MOLECULE_NAME: ${{ matrix.distro.name }}
        working-directory: ".ansible/collections/ansible_collections/rgon10/general/extensions"
