---
name: Collection Documentation
"on":
  push:
    paths-ignore:
      - ".github/workflows/ci.yml"

jobs:
  build-docs:
    permissions:
      contents: read
    name: antsibull-docs
    uses: ansible-community/github-docs-build/.github/workflows/_shared-docs-build-push.yml@main
    with:
      collection-name: rgon10.general
      init-fail-on-error: true
      squash-hierarchy: true
      init-dest-dir: docs/docsite

  pubish-docs-on-gh:
    permissions:
      contents: write
      pages: write
      id-token: write
    needs: [build-docs]
    name: Publish Ansible Docs
    uses: ansible-community/github-docs-build/.github/workflows/_shared-docs-build-publish-gh-pages.yml@main
    with:
      artifact-name: ${{ needs.build-docs.outputs.artifact-name }}
      publish-gh-pages-branch: true
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
